/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Artifact {
	contract_check: string
	host_url: string
	id: string
	parent: string | null
	registered_at: string
	standard: number
}

export interface DB {
	artifact: Artifact
}
